export * from "./privateRoute/privateRoute.component";
export * from "./header/header.component";
export * from "./cardUsuario/cardUsuario.component";
export * from "./criarPost/criarPost.component";
export * from "./comentario/comentario.component";
export * from "./comentar/comentar.component";
export * from "./post/post.component";
export * from "./amigosList/amigosList.component";
export * from "./notificacaoList/notificacaoList.component";
